


```{r, message=FALSE, warning=FALSE}
# Loading Library
library(readr)
library(igraph)
library(rsample)
library(dplyr)
library(stringr)
```



```{r}
# read data
meta <- readLines('../data/amazon-meta.txt')
```


```{r}
meta <- data.frame(line = meta, stringsAsFactors = FALSE)

filtered_meta <- meta %>%
  mutate(keep = grepl("Id:|title:|group:|categories:", line) |
                 lag(grepl("categories:", line), default = FALSE)) %>%
  filter(keep) %>%
  select(-keep)

# get row index for product that has missing info
n <- length(filtered_meta$line)
has_id <- grepl("Id: ", filtered_meta$line)

no_id_ahead <- logical(n)  # Initialize with FALSE
for (i in 1:n) {
  if (i + 5 <= n) {
    no_id_ahead[i] <- !grepl("Id:", filtered_meta[i + 5, ])
    }
  else {
    no_id_ahead[i] <- TRUE
  }
}

non_valid_indices <- which(has_id & no_id_ahead)
# fix exception: last product
non_valid_indices <- non_valid_indices[-c(5860)]

# map to df
result <- data.frame(Id = character(),
                     Title = character(),
                     Group = character(),
                     Categories = character(),
                     Subcategory = character(),
                     stringsAsFactors = FALSE)


# Process the data
i <- 1
while (i <= nrow(filtered_meta)) {
  current_row <- filtered_meta$line[i]
  if (grepl("Id:  ", current_row)) {
    # Check if there are at least three more rows and they match the expected titles
    if (i + 4 <= nrow(filtered_meta) &&
        grepl("  title: ", filtered_meta$line[i + 1]) &&
        grepl("  group: ", filtered_meta$line[i + 2]) &&
        grepl("  categories: ", filtered_meta$line[i + 3])) {
      
      # Extract and clean the data
      id <- as.integer(sub("Id:  ", "", filtered_meta$line[i]))
      title <- sub("  title: ", "", filtered_meta$line[i + 1])
      group <- sub("  group: ", "", filtered_meta$line[i + 2])
      categories <- as.integer(sub("  categories: ", "", filtered_meta$line[i + 3]))
      if (categories == 0) {
        subcategory <- NA  # Return NA if categories are 0
      }
      else if (categories > 0){
        if (group %in% c("Music", "Book", "Video")){
          sub <- filtered_meta$line[i + 4]
          subcategory <- str_split(sub, "\\|")[[1]][4] %>% str_replace_all("\\[.*?\\]", "")
          if (subcategory %in% c('Reference', 'Genres')){
            subcategory <- str_split(sub, "\\|")[[1]][5] %>% str_replace_all("\\[.*?\\]", "")
          }
        }
        else if (group == "DVD"){
          sub <- filtered_meta$line[i + 4]
          subcategory <- str_split(sub, "\\|")[[1]][5] %>% str_replace_all("\\[.*?\\]", "")
        }
      }
      # Append to result dataframe
      result <- rbind(result, data.frame(Id = id,
                                         Title = title,
                                         Group = group,
                                         Categories = categories,
                                         Subcategory = subcategory,
                                         stringsAsFactors = FALSE))
      # Move index forward by 4
      i <- i + 5
    }
    else {
      # Skip the current Id and all following rows until next Id or end of data
      i <- i + 1
      while(i <= nrow(filtered_meta) && !grepl("Id:  ", filtered_meta$line[i])) {
        i <- i + 1
      }
    }
  }
}

# write to csv
result %>% write.csv('../data/meta_data.csv')
```


```{r}
# Filter rows that contain 'Id', 'title', 'group', 'categories'
filtered_meta <- meta %>% filter(grepl('Id: |title:|group:|categories:', meta))

# get row index for product that has missing info
n <- length(filtered_meta$meta)
has_id <- grepl("Id: ", filtered_meta$meta)

no_id_ahead <- logical(n)  # Initialize with FALSE
for (i in 1:n) {
  if (i + 4 <= n) {
    no_id_ahead[i] <- !grepl("Id:", filtered_meta[i + 4, ])
    }
  else {
    no_id_ahead[i] <- TRUE  # Automatically TRUE if no such row exists
  }
}

non_valid_indices <- which(has_id & no_id_ahead)
non_valid_indices <- non_valid_indices[-c(5852)]
# drop row by index
filtered_meta <- filtered_meta[-c(non_valid_indices), ]
filtered_meta  <- data.frame(filtered_meta)
```


```{r}
# map to df
result <- data.frame(Id = character(),
                     Title = character(),
                     Group = character(),
                     Categories = character(),
                     stringsAsFactors = FALSE)

# Process the data
i <- 1
while (i <= nrow(filtered_meta)) {
  current_row <- filtered_meta$filtered_meta[i]
  if (grepl("Id:  ", current_row)) {
    # Check if there are at least three more rows and they match the expected titles
    if (i + 3 <= nrow(filtered_meta) &&
        grepl("  title: ", filtered_meta$filtered_meta[i + 1]) &&
        grepl("  group: ", filtered_meta$filtered_meta[i + 2]) &&
        grepl("  categories: ", filtered_meta$filtered_meta[i + 3])) {
      
      # Extract and clean the data
      id <- sub("Id:  ", "", filtered_meta$filtered_meta[i])
      title <- sub("  title: ", "", filtered_meta$filtered_meta[i + 1])
      group <- sub("  group: ", "", filtered_meta$filtered_meta[i + 2])
      categories <- sub("  categories: ", "", filtered_meta$filtered_meta[i + 3])
      
      # Append to result dataframe
      result <- rbind(result, data.frame(Id = as.integer(id),
                                         Title = title,
                                         Group = group,
                                         Categories = as.integer(categories),
                                         stringsAsFactors = FALSE))
      # Move index forward by 4
      i <- i + 4
    }
    else {
      # Skip the current Id and all following rows until next Id or end of data
      i <- i + 1
      while(i <= nrow(filtered_meta) && !grepl("Id:  ", filtered_meta$filtered_meta[i])) {
        i <- i + 1
      }
    }
  }
}

# write to csv
result %>% write.csv('../data/meta_data.csv')
```

